services:
  mysql:
    image: mysql:8.0
    container_name: laptop_store_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LaptopStoreDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: LaptopStore/Dockerfile
    container_name: laptop_store_backend
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=LaptopStoreDb;User=root;Password=root;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data: